In [2]:
import uproot
import numpy as np
import matplotlib.pyplot as plt

In [3]:
helix = uproot.open("/home/users/hdhoang2001/cmssw/src/RecoTracker/LSTCore/standalone/debug_hist.root")
linear = uproot.open("/home/users/hdhoang2001/cmssw/src/RecoTracker/LSTCore/standalone/linear_high_oc_hist.root")

In [4]:
import json
json.dump(helix.classnames(), open("classnames.json", "w"), indent=4)

In [5]:
helix_pT5_pt_num = helix["Root__pT5_base_0_0_ef_numer_pt"]
helix_pT5_pt_den = helix["Root__pT5_base_0_0_ef_denom_pt"]
helix_pT5_eta_num = helix["Root__pT5_base_0_0_ef_numer_eta"]
helix_pT5_eta_den = helix["Root__pT5_base_0_0_ef_denom_eta"]

linear_pT5_pt_num = linear["Root__pT5_base_0_0_ef_numer_pt"]
linear_pT5_pt_den = linear["Root__pT5_base_0_0_ef_denom_pt"]
linear_pT5_eta_num = linear["Root__pT5_base_0_0_ef_numer_eta"]
linear_pT5_eta_den = linear["Root__pT5_base_0_0_ef_denom_eta"]

In [6]:
helix_pT5_pt_bins = helix_pT5_pt_num.axis().edges()
helix_pT5_eta_bins = helix_pT5_eta_num.axis().edges()

linear_pT5_pt_bins = linear_pT5_pt_num.axis().edges()
linear_pT5_eta_bins = linear_pT5_eta_num.axis().edges()

In [8]:
helix_pT5_pt_num_vals = helix_pT5_pt_num.values()
helix_pT5_pt_den_vals = helix_pT5_pt_den.values()

linear_pT5_pt_num_vals = linear_pT5_pt_num.values()
linear_pT5_pt_den_vals = linear_pT5_pt_den.values()

array([  0.,   0.,   0.,   2., 144., 241., 224., 190., 493., 549., 658.,
       546., 500., 209., 126.,  85.])

In [9]:
sum(helix_pT5_pt_num.values())

3967.0

In [10]:
# helix_pT5_pt_den.values()

In [11]:
linear_pT5_pt_num.values()

array([  0.,   0.,   0.,   2., 142., 242., 223., 190., 496., 548., 658.,
       544., 496., 208., 126.,  85.])

In [12]:
sum(linear_pT5_pt_num.values()) 

3960.0

In [13]:
linear_pT5_pt_den.values()

array([8668., 1465., 1245.,  990.,  750.,  638.,  559.,  435., 1010.,
       1076., 1144.,  885.,  743.,  283.,  173.,  109.])

In [14]:
# helix_pT5_pt_num.errors()


In [15]:
# linear_pT5_pt_num.errors()